FROM node:9.5.0

RUN mkdir /server
WORKDIR /server


COPY server/package.json /server
RUN npm install

# Copy required server files
COPY ./server/js /server/js
COPY ./server/routes /server/routes
COPY ./server/app.js /server
COPY ./server/_config.js /server
COPY ./server/assets /server/assets

EXPOSE 8080

CMD ["npm", "start"]