version: "3"
services:
    server:
      container_name: notes
      restart: always
      image: "bookshelf-server:0.1"
      ports:
        - "8080:8080"
      links:
        - mongodb
      volumes:
        - ./client/build:/client/build
        - ./client/public:/client/public
    mongodb:
      restart: always
      container_name: mongodb
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - /data/db:/data/db
