version: '3'
services: 
  web:
    image: bookshelf
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    links:
      - mongo
  mongo: 
    image: mongo
    ports: 
      - "27017:27017"