version: "2.1"
services:
    server:
      build:
        context: .
        dockerfile: Dockerfile-server
      ports:
        - "8080:8080"
      links:
        - mongo
      depends_on:
        - mongo
    mongo:
      image: mongo
      ports:
        - "27017:27017"
