FROM node:9.5.0

RUN mkdir /server
RUN mkdir /client
WORKDIR /server


COPY package.json /server
RUN npm install

# Copy required server files
COPY ./js /server/js
COPY ./routes /server/routes
COPY ./app.js /server
COPY ./_config.js /server
COPY ./assets /server/assets

EXPOSE 8080

CMD ["npm", "start"]